/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/database/v1alpha1"
	v1alpha1network "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/network/v1alpha1"
	v1alpha1objectstorage "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/objectstorage/v1alpha1"
	v1alpha1server "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/server/v1alpha1"
	v1alpha1storage "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/storage/v1alpha1"
	v1alpha1uks "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/uks/v1alpha1"
	v1alpha1apis "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/v1alpha1"
	v1beta1 "github.com/UpCloudLtd/crossplane-provider-upcloud/apis/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1network.SchemeBuilder.AddToScheme,
		v1alpha1objectstorage.SchemeBuilder.AddToScheme,
		v1alpha1server.SchemeBuilder.AddToScheme,
		v1alpha1storage.SchemeBuilder.AddToScheme,
		v1alpha1uks.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
